/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 13:53:05 GMT 2020
 */

package model;

import exceptions.CarExistsException;
import exceptions.NoCarAvaliableException;
import exceptions.UserExistsException;
import org.junit.Test;

import static model.Car.CarType.ELECTRIC;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.file.InvalidPathException;
import model.Parser;
import model.UMCarroJa;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import utils.Point;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Parser_ESTest extends Parser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = null;
      try {
        parser0 = new Parser((String) null, uMCarroJa0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Parser parser0 = new Parser();
      boolean boolean0 = parser0.equals("MH");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = new Parser("@E@", uMCarroJa0);
      Parser parser1 = new Parser();
      // Undeclared exception!
      try { 
        parser0.equals(parser1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("model.Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = new Parser("@E@", uMCarroJa0);
      boolean boolean0 = parser0.equals(parser0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Parser parser0 = new Parser();
      boolean boolean0 = parser0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = null;
      try {
        parser0 = new Parser("Qe?(i{v^0<z8k<v:w{W", uMCarroJa0);
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Parser parser0 = new Parser();
      parser0.hashCode();
  }

  @Test
  public void testaCategoriaUser() throws UserExistsException {
      Users us = new Users();
      try {
          us.addUser(cl);
      }
      catch (Exception e) {
      }
  }

    @Test
    public void testaCategoriaCar() throws CarExistsException {
        Cars ca = new Cars();
        try {
            ca.addCar(c);
        }
        catch (Exception e) {

        }
    }

    Point p = new Point(1.1,1.2);
    Client cl = new Client(p, "X", "(951.27, 951.27)", "X", "(951.27, 951.27)", (-2452));
    Owner o = new Owner("email", "name", "address", 123456789, "passd");
    Car c = new Car("1", o, ELECTRIC, (-2234.72741484), (-2234.72741484), (-2234.72741484), 402, p, "B=`h4M7Dxt0Mo3C4o");

    @Test
    public void testaAluguer() throws NoCarAvaliableException{
        c.swapState();
        try {
            Rental r = new Rental(c, cl, p);
            r.rent();
        }
        catch (Exception e) {

        }
    }
}
