/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 14:05:00 GMT 2020
 */

package model;

import org.junit.Test;
import static org.junit.Assert.*;
import model.Weather;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Weather_ESTest extends Weather_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Weather weather0 = new Weather();
      double double0 = weather0.getSeasonDelay();
      //  // Unstable assertion: assertEquals(0.25668300441679925, double0, 0.01);
  }
}
