/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 14:26:49 GMT 2020
 */

package exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import exceptions.InvalidTimeIntervalException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InvalidTimeIntervalException_ESTest extends InvalidTimeIntervalException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InvalidTimeIntervalException invalidTimeIntervalException0 = new InvalidTimeIntervalException();
  }
}
