/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 14:25:08 GMT 2020
 */

package exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import exceptions.InvalidNewRegisterException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InvalidNewRegisterException_ESTest extends InvalidNewRegisterException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InvalidNewRegisterException invalidNewRegisterException0 = new InvalidNewRegisterException();
  }
}
