/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 14:28:49 GMT 2020
 */

package exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import exceptions.UnknownCompareTypeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UnknownCompareTypeException_ESTest extends UnknownCompareTypeException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnknownCompareTypeException unknownCompareTypeException0 = new UnknownCompareTypeException();
  }
}
