/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 13:53:05 GMT 2020
 */

package model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.file.InvalidPathException;
import model.Parser;
import model.UMCarroJa;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Parser_ESTest extends Parser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = null;
      try {
        parser0 = new Parser((String) null, uMCarroJa0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Parser parser0 = new Parser();
      boolean boolean0 = parser0.equals("MH");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = new Parser("@E@", uMCarroJa0);
      Parser parser1 = new Parser();
      // Undeclared exception!
      try { 
        parser0.equals(parser1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("model.Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = new Parser("@E@", uMCarroJa0);
      boolean boolean0 = parser0.equals(parser0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Parser parser0 = new Parser();
      boolean boolean0 = parser0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UMCarroJa uMCarroJa0 = new UMCarroJa();
      Parser parser0 = null;
      try {
        parser0 = new Parser("Qe?(i{v^0<z8k<v:w{W", uMCarroJa0);
        fail("Expecting exception: InvalidPathException");
      
      } catch(InvalidPathException e) {
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Parser parser0 = new Parser();
      parser0.hashCode();
  }
}
