/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 14:20:01 GMT 2020
 */

package model;

import org.junit.Test;
import static org.junit.Assert.*;
import model.Traffic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Traffic_ESTest extends Traffic_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Traffic traffic0 = new Traffic();
      double double0 = traffic0.getTraficDelay((-1.0));
      //  // Unstable assertion: assertEquals(0.06103560466036695, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      System.setCurrentTimeMillis(668L);
      Traffic traffic0 = new Traffic();
      double double0 = traffic0.getTraficDelay(668L);
      //  // Unstable assertion: assertEquals(0.4963470975613064, double0, 0.01);
  }
}
