/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 14:25:52 GMT 2020
 */

package view.viewmodel;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import utils.Point;
import view.viewmodel.AutonomyCar;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AutonomyCar_ESTest extends AutonomyCar_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Double double0 = new Double(1688.162833411);
      Point point0 = new Point(double0, double0);
      AutonomyCar autonomyCar0 = null;
      try {
        autonomyCar0 = new AutonomyCar(point0, 0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("view.viewmodel.AutonomyCar", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AutonomyCar autonomyCar0 = null;
      try {
        autonomyCar0 = new AutonomyCar((Point) null, 22, "A}Ga$");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("view.viewmodel.AutonomyCar", e);
      }
  }
}
