/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 14:29:47 GMT 2020
 */

package view.viewmodel;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import utils.Point;
import view.viewmodel.RegisterCar;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegisterCar_ESTest extends RegisterCar_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Double double0 = new Double(1.2);
      Point point0 = new Point(double0, double0);
      RegisterCar registerCar0 = null;
      try {
        registerCar0 = new RegisterCar((String) null, (String) null, (-702.6933622838357), (-702.6933622838357), (-849.345191900264), (-3729), point0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("view.viewmodel.RegisterCar", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Double double0 = new Double(775);
      Point point0 = new Point(double0, double0);
      RegisterCar registerCar0 = null;
      try {
        registerCar0 = new RegisterCar("ngOJkui`vE3'D-<E%^", "", 1577.240408, (-1.0), 1577.240408, 775, point0, "1b!");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("view.viewmodel.RegisterCar", e);
      }
  }
}
