/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 17 14:30:01 GMT 2020
 */

package view.viewmodel;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import view.viewmodel.RateOwnerCar;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RateOwnerCar_ESTest extends RateOwnerCar_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(0, 0);
      int int0 = rateOwnerCar0.getOwnerRate();
      assertEquals(0, rateOwnerCar0.getCarRate());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(3413, 3413);
      int int0 = rateOwnerCar0.getOwnerRate();
      assertEquals(3413, int0);
      assertEquals(3413, rateOwnerCar0.getCarRate());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(0, 0);
      int int0 = rateOwnerCar0.getCarRate();
      assertEquals(0, rateOwnerCar0.getOwnerRate());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(3413, 3413);
      int int0 = rateOwnerCar0.getCarRate();
      assertEquals(3413, rateOwnerCar0.getOwnerRate());
      assertEquals(3413, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar((-368), (-368));
      int int0 = rateOwnerCar0.getOwnerRate();
      assertEquals((-368), int0);
      assertEquals((-368), rateOwnerCar0.getCarRate());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar((-368), (-368));
      int int0 = rateOwnerCar0.getCarRate();
      assertEquals((-368), int0);
      assertEquals((-368), rateOwnerCar0.getOwnerRate());
  }
}
